apiVersion: apps/v1
kind: Deployment 
metadata:
  name: example-mysql 
  labels:
    app: example 
spec:
  selector: 
    matchLabels:
      app: example
      tier: mysql 
  template:
    metadata: 
      labels:
        app: example
        tier: mysql 
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mypassword 
          ports:
            - containerPort: 3306 
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
