apiVersion: v1 
kind: Service 
metadata:
  name: example-mysql 
  labels:
    app: example 
spec:
  ports:
    - port: 3306
  selector:
    app: example 
    tier: mysql
  type: NodePort 
---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: mysql-pv-claim 
  labels:
    app: example 
spec:
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 20Gi 
  storageClassName: standard